replicaCount: 2

image: hello-py

service:
  type: NodePort
  port: 80

greeting: "Aloha"

metrics:
  serviceMonitor:
    enable: True

externalPostgresql:
  postgresqlUsername: myuser
  postgresqlPassword: passwd
  postgresqlDatabase: myapp
  postgresqlHost: "postgres"
  postgresqlPort: "5432"
