replicaCount: 2

image: adilets/sa-assignment3-api

service:
  type: NodePort
  port: 80

greeting: "prod"

externalPostgresql:
  postgresqlUsername: myuser
  postgresqlPassword: passwd
  postgresqlDatabase: myapp
  postgresqlHost: "postgres"
  postgresqlPort: "5432"
